@users = [[id: 0,
first_name: "Jon",
last_name: "Snow",
email: "jsnow@whitewall.gov",
password: "password",
password_confirmation: "password",
role: "lender"],

[id: 1,
first_name: "Freddy",
last_name: "Francisco",
email: "freddyfrancisco@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 2,
first_name: "Florgie",
last_name: " ",
email: "florgie@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 3,
first_name: "Meng",
last_name: " ",
email: "meng@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 4,
first_name: "Murodgul",
last_name: " ",
email: "murodgul@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 5,
first_name: "Wolale C",
last_name: "Group",
email: "WolaleGroup@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 6,
first_name: "Akou",
last_name: " ",
email: "akou@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 7,
first_name: "Alejandro",
last_name: " ",
email: "alejandro@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 8,
first_name: "Mercedes",
last_name: " ",
email: "mercedes@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 9,
first_name: "David",
last_name: "Omar",
email: "davidomar@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 10,
first_name: "Tamila",
last_name: " ",
email: "tamila@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 11,
first_name: "Bugombwa",
last_name: "Kweyimukya Group",
email: "bugombwagroup@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 12,
first_name: "Abdulqader",
last_name: " ",
email: "abdulqader@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 13,
first_name: "Cleydy",
last_name: "Milka",
email: "cleydymilka@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 14,
first_name: "Rosa",
last_name: " ",
email: "rosa@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 15,
first_name: "Juliet",
last_name: " ",
email: "juliet@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 16,
first_name: "Sidy",
last_name: " ",
email: "sidy@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 17,
first_name: "Zainab",
last_name: " ",
email: "zainab@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 18,
first_name: "Ly",
last_name: " ",
email: "ly@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 19,
first_name: "Artidoro",
last_name: " ",
email: "Artidoro@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 20,
first_name: "Gopal",
last_name: " ",
email: "Gopal@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower"],

[id: 21,
first_name: "Rachel",
last_name: "Warbelow",
email: "demo+rachel@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: :default],

[id: 22,
first_name: "Jeff",
last_name: "Casimir",
email: "demo+jeff@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: :default,
nickname: 'j3'],

[id: 23,
first_name: "Jorge",
last_name: "Tellez",
email: "demo+jorge@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: :default,
nickname: 'novohispano'],

[id: 24,
first_name: "Josh",
last_name: "Cheek",
email: "demo+josh@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: :borrower,
nickname: 'josh'],

[id: 25,
first_name: "Watts",
last_name: "Watkins",
email: "demo+watts@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower",
nickname: 'watts'],

[id: 26,
first_name: "Hil",
last_name: "Denton",
email: "something@jumpstartlab.com",
password: "password",
password_confirmation: "password",
role: "borrower",
nickname: 'hildawg'],

[id: 27,
first_name: "Lender",
last_name: "McLender",
email: "lender@keevaah.com",
password: "password",
password_confirmation: "password",
role: "lender",
nickname: 'hildawg'],
]
