@loans = [  [ title: "Buy pigs for breeding and then selling",
   amount: 77500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "October 15, 2014",
   repayments_begin: "November 4, 2014",
   monthly_payment: 5500,
   category_ids: ["1"],
   user_id: 1],

  [ title: "Buy Fertilizers",
   amount: 47500,
   description: "Florgie is married with four children. Florgie is 44 years old and lives in Cabol-anonan,Tudela, Philippines. Florgie is a farmer and grows rice crops to earn a living. She has been doing this for 20 years. She has requested a loan to buy fertilizers. Florgie has been a member of PMPC for five years. In the future, Florgie hopes to save more in case of emergencies.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 8000,
   category_ids: ["1"],
   user_id: 2],

  [ title: "Buy Fertilizers and seeds",
   amount: 125000,
   description: "Meng, 35, lives in a rural village in Kampong Cham province’s Memot district, in Cambodia. He is married and has one child. For the last seven years, Meng has been farming rice and growing cassava nuts. The current business earns him about 20 USD per day to meet the family’s needs. ",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 5000,
   category_ids: ["1"],
   user_id: 3],

  [ title: "Buy young cattle",
   amount: 202500,
   description: "Murodgul comes from the town of Danghara. She is a kind and sociable 42-year-old woman who is married and the mother of two daughters [ages 17 and 16], and a 14-year-old son. Murodgul’s husband is a migrant worker and he is currently in Russia. For this reason, Murodgul takes care of her children’s education alone. At the same time, she is involved in animal husbandry at home. She started to raise cows and young bulls for resale a year ago and was initiated into the business by her brother-in-law. According to Murodgul, what she likes the most about this activity is the fact that it always provides her with milk and dairy products, as well as with a stable income. Murodgul plans to use the amount of her loan to buy a few head of young cattle in order to increase her number of domestic animals. She is hoping to receive some support, which will help her to expand her business.",
   requested_by: "October 7, 2014",
   repayments_begin: "March 4, 2015",
   monthly_payment: 15000,
   category_ids: ["1"],
   user_id: 4],

  [ title: "frais de labour, achat d’intrants, de petits matériels agricoles et de semence",
   amount: 100000,
   description: "The ten members of the Wolale C group are married women who on average are 39 years old with three children, all living in traditional families in Cinzara, a village in the municipality of San, part of the San Circle in the fourth administrative region of Mali.",
   requested_by: "March 4, 2015",
   repayments_begin: "August 7, 2015",
   monthly_payment: 10000,
   category_ids: ["1"],
   user_id: 5],

  [ title: "Purchase three sacks of corn",
   amount: 15000,
   description: "Akou is 44 years old, married, and the mother of four children. She lives in Adidogomé. She started her business selling corn porridge. Akou gets her supplies twice a month at the Assiyéyé market and sells [her product] in front of her home. Akou is seeking a loan to expand her business in order to meet the needs of her customers and make more of a profit.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 1150,
   category_ids: ["2"],
   user_id: 6],

  [ title: "Buy boats, trophies, and baseballs to sell",
   amount: 77500,
   description: "Alejandro is a visionary man who works for a local company in the town where he lives. He also earns additional income by operating a sporting goods store out of his house, which he has been doing for the past two years. Alejandro is married and his wife is a primary school teacher.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 4550,
   category_ids: ["2"],
   user_id: 7],

  [ title: "Repair dangerous home staircase",
   amount: 117500,
   description: "Mercedes is married, has a son, and lives with her parents in a brick and cement house in La Paz. The house belongs to Mercedes' mother, but is unfinished, and you could say that the wooden staircase in the home is flimsy. It needs repair.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 6000,
   category_ids: ["2"],
   user_id: 8],

  [ title: "Buy the latest video games",
   amount: 50000,
   description: "David improved his business thanks to his previous loan by purchasing a new video game console in cash. His family’s situation is now better than before. He made his loan payments on time and is teaching his children how to repair video game consoles so that in the future they can start their own business.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 3500,
   category_ids: ["2"],
   user_id: 9],

  [ title: "Purchase goods to stock and open a market",
   amount: 300000,
   description: "Tamila is 29 years old. She is married and lives with her husband, infant son, and parents-in-law in a small village of the Khulo district. Tamila and her family are involved in agricultural activities. In particular, they have 4 cows, whose milk is used to make cheese. In addition, they have 1.5 hectares of agricultural land, where they grow potatoes. The harvested potatoes and produced cheese are sold at local markets.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 15000,
   category_ids: ["2"],
   user_id: 10],

  [ title: "Pay a member's school fees",
   amount: 552500,
   description: "Josephine, whose hand is raised in the group, is a 28-year-old married woman with two children. She lives in Bundibugyo, Uganda, and her business is cocoa buying and selling. She works very hard to run her business and earn a living, and most important, to look after her children. She faces a challenge of price fluctuations, which at times lead to losses.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 69000,
   category_ids: ["3"],
   user_id: 11],

  [ title: "Pay semester school fees",
   amount: 72600,
   description: "Abdulqader is a university student majoring in Finance, and he is in his second year. Abdulqader is seeking to work in his study field after getting his bachelor’s, but he currently doesn’t have enough money to pay for his upcoming semester fees. For that, he has applied for this loan.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 4000,
   category_ids: ["3"],
   user_id: 12],

  [ title: "Cover higher education expenses",
   amount: 732500,
   description: "Cleydy is a young Dentistry student. She is asking for loan to be able to cover her education costs.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 7250,
   category_ids: ["3"],
   user_id: 13],

  [ title: "Buy butifarras-making supplies",
   amount: 75000,
   description: "Rosa, 45, earns her living making and selling butifarras, a handmade sausage made with pork and seasonings and served with wrapped yuca. It’s a family business that she started in 2004. She learned from her cousins who are very famous in their town for the quality with which they make their product. Rosa belongs to a butifarras-makers' association in Soledad, a town known for making this kind of sausage. She sells directly to local customers and referrals, through which she has gained a steady clientele.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 5000,
   category_ids: ["4"],
   user_id: 14],

  [ title: "Buy chickens and vaccines",
   amount: 50000,
   description: "Juliet is 22 years old and lives in the Gokwe South District of Zimbabwe. She is an active volunteer, serving as a Camfed Learner Guide at the local secondary school and assisting the elderly in her community. Additionally, Juliet operates a poultry business from her home. She started the business from the small savings she accumulated after being trained as a Camfed Learner Guide. Juliet has been able to support herself and her family because of her business’s success. With the loan from Keevaah, Juliet will be able to grow her business by increasing the number of broiler chickens she raises in each batch. She also intends to buy vaccines for the broilers. The profits will help in the upkeep of her family.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 6250,
   category_ids: ["4"],
   user_id: 15],

  [ title: "Buy miscellaneous goods for resale",
   amount: 102500,
   description: "Mr. Sidy is 32 years old and lives with his wife and child in a traditional family in N’tenout in the subprefecture of Ouelessebougoue [Koulikoro Region, the Republic of Mali],. Sidy did not have an opportunity to attend school. Early on he got involved in earning an income, in particular buying and reselling basic necessity goods such as soap, milk, oil, rice, flour, sugar, and beverages.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 11400,
   category_ids: ["5"],
   user_id: 16],

  [ title: "Buy beauty salon supplies",
   amount: 800000,
   description: "Zainab is a model of a spirit and determination. Although her career as a beautician started as a hobby, she developed her skills over the course of 11 years through hard work and diligent studying. Three years ago, she decided to take her career one step further and opened her own beauty salon with the support of her family.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 40000,
   category_ids: ["5"],
   user_id: 17],

  [ title: "Build a small biogas digester",
   amount: 100000,
   description: "Ly, 41 years old, is an active rice farmer in a small community in Kampong Speu Province. He has four unmarried children. To make a living and support his family, he manages and operates a rice farming business on farmland that is located near his house. He has been involved with this business since 1980 and the net profit that he can make is USD 3 a day.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 3700,
   category_ids: ["5"],
   user_id: 18],

  [ title: "Paint his residence",
   amount: 20000,
   description: "Artidoro, 40, is a loving head of household, is married, and lives in San Martin with his family. He is a person with a strong desire to get ahead. For more than five years, he has been making a living offering transportation services in a mototaxi he owns and things go well for him because he is known to his customers, he is concerned about their well-being, and he always obeys the traffic signals.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 2200,
   category_ids: ["6"],
   user_id: 19],

  [ title: "Buy cement, sand, and other materials for house repair.",
   amount: 37500,
   description: "Gopal, 42, is married. He makes a living by working as a member of the field staff at MESP NGO. His wife is a homemaker, and he has three children; all are studying in school. He’s requesting the loan from the same NGO where he is working to buy cement, sand, and other materials to repair his house because last year his house was destroyed due to heavy rain. He wants to secure his family from natural calamities, for which he needs financial support from Keevaah.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 900,
   category_ids: ["6"],
   user_id: 20],
]
